AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3.3

Metrics/LineLength:
  Max: 120
Metrics/AbcSize:
  Max: 25
Metrics/MethodLength:
  Max: 25
Metrics/ClassLength:
  Max: 150
Metrics/ParameterLists:
  Max: 7
Layout/AlignParameters:
  Enabled: false
